# Network Device Inventory
# Add your actual network devices here

devices:
  - name: "test-device"
    host: "192.168.1.10"
    device_type: "cisco_ios"
    username: "admin"
    description: "Test device for development"
    
  - name: "core-switch"
    host: "10.0.1.1" 
    device_type: "cisco_ios"
    username: "netadmin"
    description: "Core network switch"

# Supported device types:
# cisco_ios, cisco_xe, juniper, arista_eos, hp_comware