# Network Device Inventory
# Testing devices in CML

devices:
  - name: "TestRouter"
    host: "192.168.1.100"
    device_type: "cisco_ios"
    username: "admin"
    description: "CML CSR1000v Router for testing"
    
  - name: "SW1"
    host: "192.168.1.101" 
    device_type: "cisco_ios"
    username: "admin"
    description: "CML IOSv Switch for testing"

# Supported device types:
# cisco_ios, cisco_xe, juniper, arista_eos, hp_comware
# Note: Passwords handled in application for security